### ISSUE TITLE
Add support for saving collections of objects

### ISSUE THREAD

**Issue by chrisliness** [Paymentsense/Dapper.SimpleSave#1]
When trying to save a list of mapped objects I get the following exception.

Type System.Collections.Generic.IList`1[[Namespace.MyMappedType, AssemblyName, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] is not marked with a [Table] attribute. You must mark it with [Table("[schema].[tableName]")] to use it with Dapper.SimpleSave.
Parameter name: type

My method looks like this and calls simple save according:
````c#
public void Save(IList<MyMappedType> oldMyMappedType, IList<MyMappedType> newMyMappedType)
{
    using (var connection = new SqlConnection(connectionString))
    {
        connection.Open();
        connection.Update(oldFieldSellers, newFieldSellers);
    }
}
````
The following behavior would be expected:

In old list but not in new list then row should be deleted.
In old list and new list then row should be updated.
Not in old list but in new list then row should be inserted.
Not in either list then row should be ignored.

**Comment by bartread** [comment]
Behaviour is currently unsupported - have turned this into a feature request.
